services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: mlflow server --host 0.0.0.0 --backend-store-uri /mlflow --default-artifact-root /mlflow
    volumes:
      - ./mlruns:/mlflow

  svm-ser:
    build: .
    depends_on:
      - mlflow
    volumes:
      - ./shemo:/app/shemo
      - ./modified_shemo.json:/app/modified_shemo.json
      - ./mlruns:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
